server:
  port: ${PORT:0}

spring:
  devtools:
    livereload:
      enabled: false
  datasource:
    username: invoice_app
    password: 1234
    url: jdbc:postgresql://localhost:5432/invoice
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: info, health

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 2
    metadata-map:
      instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}